### ISSUE TITLE
hybpiper assemble does not respect the given `--cpu` option during blastx diamond step

### ISSUE THREAD

**Issue by etkayapar** [mossmatters/HybPiper#104]
Hello, 
We recently discovered this issue when trying to run several samples concurrently in a server with 72 cores without any job scheduling and resource management enabled (like SLURM). We set the `--cpu` parameter to 5 and tried to run two samples at the same with two independent `hybpiper` calls both using diamond instead of ncbi's blastx. The problem with it is that `hybpiper` with regular blastx splits the input to however many `--cpu` s specified with `parallel` and runs that many `blastx` processes. Enabling the `--diamond` option changes the `blastx` command with a `diamond blastx` command and running diamond without any specified number of CPUs. This is the source of the problem because `diamond` uses all available cores by default. In our case, there were two sets of five `diamond` instances, all trying to use the 72 cores at the same time. This apparently causes major slowdowns. A paired end sample with ~40 million reads one way took about 16h to complete until the end of the blasting step. For reference, running diamond manually with the same number of cores on the same sample took only 2h. 

I think explicitly stating the number of CPUs to be `1` (`-p 1`) is necessary when calling `diamond` to have the diamond version of the pipeline run the same way  as the default blast version. Completely skipping the use of `parallel` and passing the value from `--cpu` parameter of `hybpiper` to the `-p` parameter of `diamond blastx` could also be another option but I don't know if you would like to implement that.

**Comment by chrisjackson-pellicle** [comment]
Hi @etkayapar,

Ah, that's an impressive oversight on my behalf - thanks for bringing it to our attention! 

The use the native `-num_threads` / `--threads` parameters for NCBI and DIAMOND blastx, vs the way HybPiper currently does it (i.e. chunking the file and running multiple BLAST instances via GNU parallel) is something we've been meaning to look in to. The latter approach was inherited from HybPiper version 1.3, and I believe it was written that way to reduce RAM usage back at a time when most laptops had much less RAM available.

I've just run some quick tests for DIAMOND blastx, using an unzipped read file with 8,752,192 sequences and 5 threads:

**Current HybPiper approach (file chunking and `diamond blastx` via GNU parallel):**
   - 15 mins 19 seconds
   - RAM Resident Set Size 127 MB

**Native `--threads` option to the `diamond blastx` command, using the entire read file as input:**
   - 2 mins 44 seconds
   - RAM Resident Set Size 5.7 GB

So, using the native `--threads` option is much faster, and uses much more RAM.

Similar tests with a smaller dataset (the latter largely because the tests were taking too long) using NCBI blastx show the opposite pattern. Using a read file with 305,947 sequences and 20 threads:

**Current HybPiper approach (file chunking and `blastx` via GNU parallel):**
   - 2 mins 12 seconds
   - RAM Resident Set Size 1.34 GB

**Native `-num_threads` option to the  `blastx` command, using the entire read file (converted to fasta first as NCBI blastx doesn't take fastq) as input:**
   - 22 mins 3 seconds
   - RAM Resident Set Size 77 MB

While this is very rough testing, and doesn't compare a range of read and database sizes, it looks like it might be best to do the following:

1) DIAMOND blastx. Remove gunzip and on-the-fly fastq to fasta conversion (as DIAMOND supports fastq and *.gz input), and remove read chunking and GNU parallel stages. Instead, pass the `hybpiper assemble` `--cpu` value to the DIAMOND `--threads` parameter directly. Add a flag to the `hybpiper assemble` command called e.g. `--diamond_low_mem`, which restores the `cat | awk | parallel | diamond blast` approach.

2) NCBI blastx. Keep everything as is, i.e. gunzip read files if necessary, chunk and perform on-the-fly fastq to fasta  conversion, and pass the `hybpiper assemble` `--cpu` value to GNU parallel, which then runs multiple instances of blastx with a hardcoded `-num_threads 1`.

Does that sound like a reasonable solution, to you?

Cheers,

Chris

**Comment by etkayapar** [comment]
Hi @chrisjackson-pellicle, 

Thank you for your tests and your response! As a user, your implementation suggestions seem reasonable to me. 
My only problem is with the point number 1 (DIAMOND blastx), specifically the `--diamond_low_mem` option. I think a hardcoded `--threads 1` would still be necessary for that case because otherwise each parallel diamond process will try to use all available cores of the machine.

Cheers,
Etka
