### ISSUE TITLE
Much lower recovery from HybPiper 2.1 than 1.3

### ISSUE THREAD

**Issue by V-Z** [mossmatters/HybPiper#122]
Hello,
if I take identical high-quality FASTQ samples and run in HybPiper 1.3

```bash
# For each sample
python3 reads_first.py --bwa -r "${SAMPLES}".R{1,2}.fq -b "${BAITFILE}" --cpu "${NCPU}" --prefix "${SAMPLES}"
python3 paralog_investigator.py "${SAMPLES}"
python3 intronerate.py --prefix "${SAMPLES}" --addN
python3 depth_calculator.py --targets "${BAITFILE}" -r "${SAMPLES}".R{1,2}.fq --prefix "${SAMPLES}"
python3 cleanup.py "${SAMPLES}"
# And then summary
python3 get_seq_lengths.py "${BAITFILE}" "${SAMPLES}" dna > seq_lengths.txt
python3 hybpiper_stats.py seq_lengths.txt "${SAMPLES}" > stats.txt
python3 retrieve_sequences.py "${BAITFILE}" . dna
python3 retrieve_sequences.py "${BAITFILE}" . intron
python3 retrieve_sequences.py "${BAITFILE}" . supercontig
```

I get about 85% COS probes recovered, which seems fine. But if I run with **same** samples in HybPiper 2.1.3

```bash
# For each sample
hybpiper assemble --readfiles "${SAMPLES}".R{1,2}.fq --targetfile_dna "${BAITFILE}" --bwa --cpu "${NCPU}" --prefix "${SAMPLES}" --run_intronerate
# And then summary
hybpiper stats --targetfile_dna "${BAITFILE}" gene samples_list.txt
hybpiper retrieve_sequences --targetfile_dna "${BAITFILE}" --sample_names samples_list.txt dna
hybpiper retrieve_sequences --targetfile_dna "${BAITFILE}" --sample_names samples_list.txt intron
hybpiper retrieve_sequences --targetfile_dna "${BAITFILE}" --sample_names samples_list.txt supercontig
hybpiper paralog_retriever --targetfile_dna "${BAITFILE}" samples_list.txt
```

I get about 30-40% of probes recovered (more for exons, very low for introns and supercontigs), which is weird. Moreover, a lot of them are very short, so they easily get discarded when I trim the alignments. So I wonder what could be the problem...?

**Comment by V-Z** [comment]
Hm, as looking at changelog, it's probably doe to bug in 2.1.3, which should be fixed in upcoming 2.1.5, so I hope it'll be released soon. :-)

**Comment by chrisjackson-pellicle** [comment]
Hi @V-Z,

I just made a release for v2.1.5, and the conda packages are updated. Can you try that, and see how you go? If the issue persists we can take a closer look at it.

Cheers,

Chris

**Comment by V-Z** [comment]
Hi, thank You, it seems to be fine now. :-)

**Comment by chrisjackson-pellicle** [comment]
Great, thanks for letting me know!

**Comment by V-Z** [comment]
Sorry, I'll have to reopen this after more experiments. 😟 The situation with 2.1.5 is much better than with 2.1.3, but not so good as with 1.3 regarding sequence recovery. Let's consider example with 1061 COS probes (for Asteraceae).

* Total number of recovered contigs (should be up to 3183 (3*1061))
  * HybPiper 1.3: 2642 (over 83%) in average per sample
  * HybPiper 2.1.5: 2030 (almost 64%) in average per sample
  * Numbers are from counting of samples in FASTA and FNA files after HybPiper postprocessing. Interestingly, column `GenesWithSeqs` from HybPiper statistics gives similar numbers in both cases.
  * Generally it seems 2.1.5 often produces much shorter sequences, especially in introns, so they are easily removed during trimming of alignments ([see what I use](https://github.com/V-Z/hybseq-scripts/blob/master/bin/hybseq_4_alignment_3_run.r)).
* And when I align contigs and do [trimming](https://github.com/V-Z/hybseq-scripts/blob/master/bin/hybseq_4_alignment_3_run.r), I get
  * HybPiper 1.3
    * 1029 exons, each sample is in average in 82% of alignments; average length is 301 bp
    * 1020 introns, each sample is in average in 69% of alignments; average length is 591 bp
    * 1029 supercontigs, each sample is in average in 75% of alignments; average length is 879 bp
  * HybPiper 2.1.5: 864 exons, 693 introns and 864 supercontigs
    * 864 exons, each sample is in average in 87% of alignments; average length is 307 bp
    * 693 introns, each sample is in average in 19% of alignments; average length is 158 bp --- I think it produces mainly very short sequences, which easily get trimmed out.
    * 864 supercontigs, each sample is in average in 82% of alignments; average length is 880 bp
  * As I start with identical FASTQ files and I do same trimming, I'd expect basically same results.

So still I think there is some problem in HybPiper 2.1.5. I'd like to investigate this further, as this issue is weird.

**Comment by chrisjackson-pellicle** [comment]
Hi @V-Z,

No problem, it'll be good to get to the bottom of this.

Can you upload your `hybpiper_stats` file for both the 1.3 and 2.1.5 run?

Cheers,

Chris

**Comment by V-Z** [comment]
Here are statistics and logs for both 1.3 and 2.1.5: [stats.zip](https://github.com/mossmatters/HybPiper/files/12066747/stats.zip).

**Comment by chrisjackson-pellicle** [comment]
Thanks for those files.

The two stats file have different numbers of samples, though, and there are samples present in `stats.txt` that aren't in `hybpiper_stats.tsv`, and vice-versa. Did you mean to send those particular files?

It may not be the comparison we're after if the stats files are mixed up, but I compared the 'GenesWithSeqs'  and 'GenesAt75pct' values for taxa that were in both files, and almost without exception that values are higher for HybPiper v2 than those for HybPiper v1.3 (it looks like the HybPiper 2 run for `Pteronia_tricephala_R546` failed completely - all the stats values are zero).  Here's the comparsion report:

[compare_stats.tsv.zip](https://github.com/mossmatters/HybPiper/files/12067926/compare_stats.tsv.zip)

So, things look fine as far as the stats go (with the file issue caveat). Have you had a look at some of the raw alignments, and compared them for the same gene for HybPiper v2 vs v1.3? Do the HybPiper v2 sequences looks more anomalous, and hence indicate an issue with HybPiper v2 assembly?

Cheers,

Chris

**Comment by V-Z** [comment]
Thanks for checking. Yes, the sets are not identical, few samples were also renamed in meantime due to improved identification, but it doesn't blur general picture.

What does confuse me a lot is that if I [calculate presence of samples in contigs](https://github.com/V-Z/hybseq-scripts/blob/master/bin/hybseq_3_hybpiper_postprocess_2_run.sh#L156) I get much lower numbers for 2.1.5 (compare both `presence_of_samples_in_contigs.tsv`). With 1.3 I get correct numbers.

When I check alignments, for exons, I more often see very short ones, and higher proportion of bad alignments, although main problem is I simply have less samples there. I don't see ambiguous basis, but higher number of missing data. Extremely bad are introns with 2.1.5. Wild guess would be some issue with mapping and/or assembly. See also [statistics of alignments](https://github.com/mossmatters/HybPiper/files/12068857/Archiv.zip). Otherwise, I don't know what can be source of the differences.

**Comment by joyceem** [comment]
Hi there, 

I just wanted to chip in with my 2 cents in here as well: I've been getting the same sort of issue, but where HybPiper v 2.1.3 and 2.1.5 is retrieving a much lower number of genes with sequences than version 2.0. This is with the Angiosperm 353 baits.

I haven't got the results of a direct comparison yet because so far I've run the different versions of HybPiper on the same samples but with slightly different target files (fixed vs. unfixed). However I am running two identical runs now with different versions of HybPiper and can see that as they progress I'm only getting c. 30% of the sequences in v. 2.1.5 compared to v. 2.0. I can send you through the results of that direct comparison when they have finished at the end of the week if it is of interest.

I think it is an issue with exonerate, because the alignments look ok to me? Further, when I use the output of HybPiper v. 2.1.3 and take it to HybPhaser to remap the reads, the number of sequences retrieved in HybPhaser is much higher (and closer to what I was getting in v 2.0).

I've attached the HybPiper v2.1.3 stats.csv and a couple of the .log files, as well as the summary of the results from taking the output of the HybPiper v2.1.3 samples through HybPhaser.

Let me know if I can provide any more info.

Many thanks,
Lizzy

[github hybpiper troubleshooting.zip](https://github.com/mossmatters/HybPiper/files/12069114/github.hybpiper.troubleshooting.zip)

**Comment by chrisjackson-pellicle** [comment]
Hi @V-Z,

I think troubleshooting this will be easier if we examine the direct outputs of HybPiper v1.3 and v2.1.5 for the same samples, rather than post-processed alignments from different sample sets. 

At the moment, if I've understood correctly, your HybPiper v1.3 dataset has 362 samples, your HybPiper v2.1.5 dataset has 402 samples, and 284 samples are common to both datasets. You're then generating recovery stats from alignments that have been processed to remove first columns then rows, based on a proportion of gaps. As your alignments for a given gene likely have different samples (and total number of samples) when comparing your v1.3 and v2.1.5 analyses, they'll likely have different gap profiles, and so the outcome of applying gap-based trimming with the same thresholds could be quite different. Moreover, the stats files produced by HybPiper suggest that for exon sequences from samples common to both datasets, v2.1.5 is producing sequences for more genes that v1.3, and those sequences are longer.

Regarding your 'presence of samples in contigs' stats - I see from your script that it's a combined count of exon, intron and supercontig sequences. As I described above, HybPiper v2 will produce fewer sequences for introns than v1.3, so this will reduce your combined count for v2.

You mentioned that when you check alignments for exons, you more often see very short ones, and a higher proportion of bad alignments, although the main problem is that there are simply fewer samples. Can you upload raw alignments (i.e. before your gap-based processing) for v1.3 and 2.1.5 for a couple of genes, showing these differences from samples that are common to both datasets?

Focusing on exons for the moment, I guess the questions we want to answer are:

When comparing output from HybPiper 1.3 and 2.1.5 for the same sample, does HybPiper 2.1.5:

1. Fail to produce a sequence, whereas v1.3 does produce a sequence
2. Produce a sequence that's shorter than the sequence from v1.3
3.  Produce a sequence that looks dodgy in some way (e.g. regions of high divergence and poor   alignment that might suggest mistakes in the sequence assembly.
4. A combination of 2 and 3

Cheers,

Chris

**Comment by chrisjackson-pellicle** [comment]
Hi @joyceem  - can you open this as a separate issue? It looks like there are a couple of problems to deal with - your sample log files show that the exonerate_contigs step of the pipeline failed for a bunch of genes. Also, in your stats file the column 'GenesWithSeqs' has lower values than the 'GenesAt25pct', which shouldn't be happening, and might be a bug in HybPiper that needs fixing. When you open the new issue, can you upload the `seq_lengths.tsv` files for the samples you provided the log files for?

Cheers,

Chris

**Comment by joyceem** [comment]
Hi @chrisjackson-pellicle 

Thanks for looking into this! I will open a new issue with the log files, stats and seq lengths for samples run with v2.0 vs. 2.1.5.

Cheers
Lizzy

**Comment by V-Z** [comment]
Hi, @chrisjackson-pellicle, sorry for late reply. I had to re-run everything and I had little technical issues with our cluster.

So I have run for 1.3 and 2.1.5 with 284 identical samples as starting point. [Archiv.zip](https://github.com/mossmatters/HybPiper/files/12173505/Archiv.zip)

First, I was not aware that low recovery of introns is feature of v. 2+ (May I ask why is it so?), sorry, it indeed does skew statistics a lot. I get
* 1.3: in average over 82% of sequences per sample (same for exons, introns as well as supercontigs)
* 2.1.5: in average 85% of exons, 18.5% of introns and 85% of supercontigs

So 2.1.5 is slightly better, if we disregard introns. So far so good.

If I look at alignments (all processed in same way), I get:
* 1.3: in average 78% of samples in exons (average length 299 bp), 65% in introns (average length 590 bp) and 72% in supercontigs (average length 878 bp)
* 2.1.5: in average 82% of samples in exons (average length 299 bp), 17% in introns (average length 162 bp) and 76% in supercontigs (average length 873 bp)

Otherwise alignments from both sets seem to be similar. So it seems that observed differences were due to issue with introns, and differences in samples sets (some low quality could also influence stats a lot). I'm also influencing some technical issue, as the numbers are very different ("common problems" I check, so it's weird).
