### ISSUE TITLE
hybpiper assemble runs but SPAdes assemblies are only made for 1 gene

### ISSUE THREAD

**Issue by mheeney** [mossmatters/HybPiper#158]
Hello,

hybpiper assemble runs but SPAdes assemblies and all other outputs are only made for 1 gene/feature in the reference fasta. I believe it has to do with my reference fasta because everything ran fine with an alternative reference but the same fastq files. 

I have attached all of the different logs. I also tried running check_targetfile followed by fix_targetfile and it doesn't seem to have changed the issue although it did change the fasta reference. 

[SRR7279494_hybpiper_assemble_2024-08-30-09_08_27.log](https://github.com/user-attachments/files/16818457/SRR7279494_hybpiper_assemble_2024-08-30-09_08_27.log)
[fix_targetfile_2024-08-30-09_01_58.log](https://github.com/user-attachments/files/16818458/fix_targetfile_2024-08-30-09_01_58.log)
[spades.log](https://github.com/user-attachments/files/16818459/spades.log)

**Comment by chrisjackson-pellicle** [comment]
Hi @mheeney,

This is happening because of the way the sequences are named in your target file, i.e.,:

```
mRNA-Solyc07g006690-3-1
mRNA-Solyc07g006720-4-1
```

As described [here](https://github.com/mossmatters/HybPiper/wiki#12-target-file), HybPiper requires that the identifier after the final dash (`-`) in your sequence names is unique for each gene/locus, whereas all of your sequences have the identifier `1`.

Cheers,

Chris

**Comment by chrisjackson-pellicle** [comment]
I'll close this issue, but feel free to re-open it if it's still a problem.

Cheers,

Chris
