### ISSUE TITLE
get_seq_lengths.py and hybpiper_stats.py issues

### ISSUE THREAD

**Issue by perla-far** [mossmatters/HybPiper#65]
Hello,
when I run the script get_seq_lengths.py, it works but it give a txt file for which at the end of the file, there are 3 rows with the value "0". These 3 rows are not assigned to any sample (screenshot below). 
I am not sure why I have this result. please if you can help in this issue it would be great. 
As well, I have an error when I run the hybpiper_stats.py (I have tried using the output text file from the script get_seq_lengths.py including and excluding the values "0" at the end of the file). This error indicate that the .Bam file could not be found (screenshot below).
I have followed the same folder' hierarchy of the "test_dataset".
please let me know how can I fix these issues

Thank you so much

![image](https://user-images.githubusercontent.com/87534141/125961865-2dc84124-cd76-44b4-be78-24fa167de367.png)
![image](https://user-images.githubusercontent.com/87534141/125962685-0552806a-bdac-40de-8c8f-4aa8ee1b99d7.png)

**Comment by chrisjackson-pellicle** [comment]
Hi @perla-far,

Are you using a `namelist.txt` file that has empty lines at the end? If so, that's the likely cause of what you're seeing. If you're running HybPiper version 1.3, you can simply delete the empty lines and run `get_seq_lengths.py` and `hybpiper_stats.py` again. Alternatively, this has been fixed in HybPiper2 version 2.0.1rc build 12 - empty lines in your `namelist.txt` file are now ignored. 

Cheers,

Chris

**Comment by chrisjackson-pellicle** [comment]
Hi @perla-far - I'm closing this issue now, but feel free to re-open it if you still have a problem with this.
