### ISSUE TITLE
Array HPC job

### ISSUE THREAD

**Issue by isgilman** [mossmatters/HybPiper#68]
Hi Matt,

I've got a question about HybPiper implementation on HPCs. We use the SLURM manager, but I think it's more general. When running multiple samples the tutorials suggest creating a `namelist.txt` file and iterating over a `while` loop. From my understanding, this will generally be slower than running an array job that lets a separate node handle each sample. Is there a reason that this approach is used? Maybe some information is passed along the way, or to avoid multiple sources writing to a shared file that is carried throughout the analysis?

Thanks,
Ian

**Comment by mossmatters** [comment]
Ian, 

I think the loop on a single machine was mainly based on the HPCC architecture I had access to when I wrote the wiki. In that particular cluster it made more sense to just reserve one node for a while, rather than send dozens of jobs to the queue. 

But now as the number of reads (and samples) is increasing for many projects I see the advantage of the array job. It  should be totally fine, there's no communication across samples and all the error logging is done per sample. In other array jobs I have still used a `namelist.txt` but accessed it using the array ID number used by the queuing system:

`name=$(tail -n $JOB_ARRAY_ID namelist.txt | head -1)`

Hope that helps!

~Matt

**Comment by isgilman** [comment]
Ah that's much more readable than my copy-and-paste the nameslist file contents! Thank you!
