### ISSUE TITLE
Problems executing spades.py

### ISSUE THREAD

**Issue by RY970709** [mossmatters/HybPiper#71]
I have encountered the following problem when executing the spades.py script, and I don't know how to solve it, I hope I can get your help, thanks!
———————————————————————————————————————————————————————————
[NOTE]:    15 genes had no good matches.
[NOTE]:    Running initial SPAdes assemblies for 8129 genes with reads...
[CMD]:     time parallel --joblog gnu_parallel_log.txt --eta spades.py --only-assembler
           --threads 1 --cov-cutoff 8 --12 {}/{}_interleaved.fasta -o {}/{}_spades ::::
           spades_genelist.txt > spades.log
**sh: /dev/tty: No such device or address**

Computers / CPU cores / Max jobs to run
1:local / 112 / 112

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
ETA: 0s Left: 8128 AVG: 0.00s  local:112/1/100%/2.0s sh: /dev/tty: No such device or address
ETA: 8099s Left: 8127 AVG: 0.50s  local:112/2/100%/1.5s sh: /dev/tty: No such device or address
ETA: 8099s Left: 8127 AVG: 1.00s  local:112/2/100%/2.0s sh: /dev/tty: No such device or address

**Comment by chrisjackson-pellicle** [comment]
Hi @RY970709,

Firstly, you should able to safely ignore the  `sh: /dev/tty: No such device or address` error message in this case. Did HybPiper continue running, and finish successfully?

Secondly, did you happen to launch HybPiper via a scheduling system (SLURM, PBS etc)? If so, this error occurs when using the `--eta` flag with `parallel`. Again, the error can be safely ignored in this case. A future release of HybPiper will run SPAdes via Python's multiprocessing instead of `parallel`, and this error will no longer occur.

Cheers,

Chris

**Comment by RY970709** [comment]
> Hi @RY970709,
> 
> Firstly, you should able to safely ignore the `sh: /dev/tty: No such device or address` error message in this case. Did HybPiper continue running, and finish successfully?
> 
> Secondly, did you happen to launch HybPiper via a scheduling system (SLURM, PBS etc)? If so, this error occurs when using the `--eta` flag with `parallel`. Again, the error can be safely ignored in this case. A future release of HybPiper will run SPAdes via Python's multiprocessing instead of `parallel`, and this error will no longer occur.
> 
> Cheers,
> 
> Chris

Yes, I noticed that the software continued to run after this issue and successfully generated the corresponding result files. I was initially worried about the impact on the results, so I came here to ask about it, thank you for your answer, now I can continue the downstream analysis with confidence!
