### ISSUE TITLE
error with exonerate in new HybPiper version

### ISSUE THREAD

**Issue by MareikeJaniak** [mossmatters/HybPiper#72]
Hi!

I've just used the new version of HybPiper for the first time after using 1.3 for a while. I'm running into an issue with exonerate for most of the genes I'm trying to assemble and I was hoping you could shed some light on it. 

For gene ADH7 exonerate() raised: [Errno 2] No such file or directory: 'ADH7/ApalMelin/chimera_test_stitched_contig.sam'
error.traceback is: Traceback (most recent call last):
  File "/home/mcj43/virtual_env/hybpiper_env/lib/python3.8/site-packages/pebble/common.py", line 170, in process_execute
    return function(*args, **kwargs)
  File "/home/mcj43/virtual_env/hybpiper_env/lib/python3.8/site-packages/hybpiper/assemble.py", line 919, in exonerate
    exonerate_result = exonerate_hits.parse_exonerate_and_get_stitched_contig(
  File "/home/mcj43/virtual_env/hybpiper_env/lib/python3.8/site-packages/hybpiper/exonerate_hits.py", line 520, in parse_exonerate_and_get_stitched_contig
    exonerate_result = Exonerate(searchio_object=exonerate_hits_from_alignment,
  File "/home/mcj43/virtual_env/hybpiper_env/lib/python3.8/site-packages/hybpiper/exonerate_hits.py", line 642, in __init__
    self.chimera_warning_bool = self._stitched_contig_chimera_warning()
  File "/home/mcj43/virtual_env/hybpiper_env/lib/python3.8/site-packages/hybpiper/exonerate_hits.py", line 1453, in _stitched_contig_chimera_warning
    with open(f'{self.prefix}/chimera_test_stitched_contig.sam') as samfile:
FileNotFoundError: [Errno 2] No such file or directory: 'ADH7/ApalMelin/chimera_test_stitched_contig.sam'

This is happening for ~112/125 genes, even though they previously assembled fine with v1.3. 

Thanks!

Best, 
Mareike

**Comment by chrisjackson-pellicle** [comment]
Hi Mareike,

Thanks for raising this issue. To help diagnose it, can you send me:

1) The output of running `hybpiper -v`

2) The log file for the sample with the error. It will be located within the sample directory, and will be named `ApalMelin_hybpiper_assemble_<year-date-time>.log`

Also, from the file path in the error message, it looks like you installed HybPiper manually in a `virtual_env` - is that correct?

Cheers,

Chris

**Comment by MareikeJaniak** [comment]
Hi Chris, 

Thanks for the quick response!

1. The output of `hybpiper -v` is the ascii art followed by: hybpiper 2.0rc build 7. However: I could not find biopython 1.80 (is it a development version?), so I am running 1.79 and I had to comment out the check for biopython version > 1.80 to get hybpiper to run. It runs fine on the test dataset, though, even with 1.79. 

2. The log file is attached. (This is for a different sample, but it was getting the same error.) I skimmed it and I noticed that a bbmap step might have gotten killed, so maybe this is just a memory issue? It looked like the job finished without issues, but I just checked the stats from the job scheduler (SLURM) and it does say "State: OUT_OF_MEMORY (exit code 0)" 

3. Yes, I had to install HybPiper manually, unfortunately. I'm working on an HPC (compute canada) that doesn't allow users to use conda and encourages us to use virtual environments instead (reasons here, if you're interested: https://docs.computecanada.ca/wiki/Anaconda/en)


[AgeoMelin_hybpiper_assemble_2022-05-13-10_05_17.log](https://github.com/mossmatters/HybPiper/files/8691723/AgeoMelin_hybpiper_assemble_2022-05-13-10_05_17.log)

**Comment by chrisjackson-pellicle** [comment]
Hi Mareike,

Ah, yes, it does look like `bbmap` is getting killed by your HPC. It's the `bbmap` step that produces the `chimera_test_stitched_contig.sam` file - it's absence is causing the `FileNotFoundError: [Errno 2] No such file or directory: 'ADH7/ApalMelin/chimera_test_stitched_contig.sam'` in your error above.

I notice in your log file that you aren't using the `--cpu` flag to specify the number of cpus. This means that HybPiper will use all available cpus. The Exonerate step of the pipeline is run in parallel, with the number of genes being processed at one time corresponding to the number of cpus. As each Exonerate process often launches bbmap using ~1GB RAM (user adjustable with the `--bbmap_memory` parameter, although the default 1GB has been fine for all our test datasets, and going lower results in out-of-memory errors), this can result in high RAM usage when the number of cpus is large. Are you submitting the HybPiper run via a scheduler (SLURM, PBS, etc)? If so, what are your cpu and RAM requests in the submission script? You might benefit from adjusting them. Alternatively, if you're running on an interactive node with a set amount of memory, using the `--cpu` flag to limit the number of cpus (and hence limit the amount of RAM used by bbmap at any given time) might be helpful.

Regarding Biopython 1.80 - yes, it hasn't been released yet. It's bundled with the conda install, but if you're installing manually you can clone the current repo at https://github.com/biopython/biopython, and install it following the instructions under 'Installation from Source' here: https://biopython.org/wiki/Download. While 1.79 might be fine with some datasets, it will produce errors with others. HybPiper 2.0 uses the Biopython SearchIO module to parse the text output of Exonerate, and there were bugs in 1.79 that I've fixed in 1.80.

I'll add the instructions for manual installation of Biopython 1.80 to the wiki, and I'll add an INFO message to HybPiper's output to remind users that they're using all available cpus when not using the `--cpu` parameter.  

Let me know how you go!

Cheers,

Chris

**Comment by MareikeJaniak** [comment]
Hi Chris, 

Thanks for the thorough response - that makes sense! Yes, I'm requesting 12 cpus and 8GB memory per job, which is probably the issue. This previously worked well, but of course v1.3 didn't have the bbmap step. 

I will adjust all of this on Monday and report back! Have a nice weekend!

Best, 
Mareike

**Comment by MareikeJaniak** [comment]
Hi Chris, 

I've installed the development version of biopython and changed my memory request for the jobs sent out on the cluster, and I also added the --bbmap_memory and --cpu flags to my hybpiper command. The SLURM status of the jobs no longer says OUT OF MEMORY, but COMPLETED and I don't see the entries about bbmap.sh getting killed in the log file. So there's progress! 

However (sorry!), exonerate is still failing for the majority of my genes with this error message:

For gene ADH7 exonerate() raised: [Errno 2] No such file or directory: 'ADH7/AgeoMelin/chimera_test_stitched_contig.sam'
error.traceback is: Traceback (most recent call last):
  File "/home/mcj43/virtual_env/hybpiper_env/lib/python3.8/site-packages/pebble/common.py", line 170, in process_execute
    return function(*args, **kwargs)
  File "/home/mcj43/virtual_env/hybpiper_env/lib/python3.8/site-packages/hybpiper/assemble.py", line 919, in exonerate
    exonerate_result = exonerate_hits.parse_exonerate_and_get_stitched_contig(
  File "/home/mcj43/virtual_env/hybpiper_env/lib/python3.8/site-packages/hybpiper/exonerate_hits.py", line 520, in parse_exonerate_and_get_stitched_contig
    exonerate_result = Exonerate(searchio_object=exonerate_hits_from_alignment,
  File "/home/mcj43/virtual_env/hybpiper_env/lib/python3.8/site-packages/hybpiper/exonerate_hits.py", line 642, in __init__
    self.chimera_warning_bool = self._stitched_contig_chimera_warning()
  File "/home/mcj43/virtual_env/hybpiper_env/lib/python3.8/site-packages/hybpiper/exonerate_hits.py", line 1453, in _stitched_contig_chimera_warning
    with open(f'{self.prefix}/chimera_test_stitched_contig.sam') as samfile:
FileNotFoundError: [Errno 2] No such file or directory: 'ADH7/AgeoMelin/chimera_test_stitched_contig.sam'


I'm attaching the log file for one of my jobs and also the log file from the ADH7 gene directory as an example - there is something still going wrong with bbmap, but I'm not quite sure what it is. 

Thanks for your help!

Best, 
Mareike

[ADH7_2022-05-17-16_47_55.log](https://github.com/mossmatters/HybPiper/files/8712297/ADH7_2022-05-17-16_47_55.log)
[AgeoMelin_hybpiper_assemble_2022-05-17-09_54_44.log](https://github.com/mossmatters/HybPiper/files/8712298/AgeoMelin_hybpiper_assemble_2022-05-17-09_54_44.log)

**Comment by chrisjackson-pellicle** [comment]
Hi Mareike,

Progress indeed!

I see from your log file that you've used the parameter `--bbmap_memory 1`. In HybPiper the integer provided to `--bbmap_memory` is passed on to the `bbmap.sh` command as megabytes of RAM, rather than gigabytes, so in this case you've restricted `bbmap.sh` to 1 MB. You can see this in the log file from the ADH7 gene directory (good thinking to send this, thanks) on line 9, where it says `.... bbmap_command FAILED. Output is: Command 'bbmap.sh -Xmx1m ...`. For Java programs the maximum memory is set via the `-Xmx` parameter, and here you can see the integer is followed by an `m` for megabytes - it could also be provided as `g` for gigabytes, but I thought megabytes would allow for more (probably unnecessary) fine-grained control. 

So, you could leave the `--bbmap_memory` parameter off entirely and see how it goes (the default value is 1000 MB), or increase it if your HPC node allows.

Cheers,

Chris

**Comment by MareikeJaniak** [comment]
Hi Chris,

Aha! No wonder bbmap wasn't getting anywhere with that restriction! Obviously meant 1GB there, but if that's the default anyway, I'll try just removing the --bbmap_memory flag. 

Best, 
Mareike

**Comment by chrisjackson-pellicle** [comment]
I've just pushed HybPiper version 2.0.1 to the git repo and the conda packages. Now, when `bbmap.sh` fails, HybPiper logs a message to screen and logs the error details to the main `*.log` file in the sample directory, but continues to process the gene without running a stitched-contig chimera test. Hopefully that's less obtuse than the error message you came across!

Cheers,

Chris

**Comment by chrisjackson-pellicle** [comment]
Good to hear - and no problem! I'll close this issue now.
