### ISSUE TITLE
pyqt error_unable to create graphs

### ISSUE THREAD

**Issue by abedoya250** [mossmatters/HybPiper#77]
Hello,

When trying to create the graphs with recovery_heatmap and paralog_retriever in my ubuntu 21.10 machine, I get 
symbol lookup error: /home/miniconda3/plugins/platforms/../../lib/libQt5XcbQpa.so.5: undefined symbol: _ZN22QWindowSystemInterface24setPlatformFiltersEventsEb, version Qt_5_PRIVATE_API

I suspect this may have something to do with the configuration in my computer but was wondering if you have suggestions of how to fix this.

Thanks in advance

**Comment by chrisjackson-pellicle** [comment]
Hi @abedoya250,

I haven't come across this issue myself before. However, it looks like you have Qt shared libraries installed in your conda `base` environment (i.e. path `/home/miniconda3/plugins/platforms/../../lib`), and these are being used when you run HybPiper instead of the ones installed in your `hybpiper` environment (for example, on my system the Qt shared libraries in my `hybpiper` environment are at `/home/cjackson/.conda/envs/hybpiper/lib/libQt5*`. 

I've occasionally seen conda  do odd things with paths that have been fixed by deactivating all conda environments, including the `base` environment, and then activating the required environment only (`conda activate hybpiper`, in this case). Have you tried that?

Looking at cases where people have run in this problem with other software (e.g. https://github.com/napari/napari/issues/2309), it looks like it can sometimes be caused when the environment variable [QT_QPA_PLATFORM_PLUGIN_PATH](https://github.com/napari/napari/issues/2309#issuecomment-787824141) is set in a way that overrides the Qt libraries in the active conda environment. Might be worth checking?

Let me know how you go,

Cheers,

Chris

**Comment by AMBedoyaO** [comment]
Hi Chris,

Super useful response. Thank you! Yes, I installed hybpiper using conda and creating a new environment. Indeed, the problem was because the QT_PLUGIN_PATH was specified as an environment variable. I removed it and everything works great now. Hope this helps other folks if they experience this same issue.

**Comment by chrisjackson-pellicle** [comment]
Excellent, good to know!
