### ISSUE TITLE
Should FAA translation be used for FNA targetfiles that are not multiples of 3?

### ISSUE THREAD

**Issue by BenKuhnhaeuser** [mossmatters/HybPiper#82]
Hi Matt,
I have seen on the wiki that you have found that using BLASTx with an FAA targetfile usually yields better results than using BWA with an FNA targetfile. My targetfile, however, has many "genes" with lengths that are not multiples of three bases, so I fear that the reading frames will often be incorrect. Do you think that will have a negative impact on gene assembly and that in such cases the original FNA targetfile should be used instead?
Many thanks,
Ben

**Comment by chrisjackson-pellicle** [comment]
Hi Ben,

I wrote that Wiki section, so I thought I'd jump in and clarify if I can!

**Short summary:**

If your target file contains sequences that are closely related to your samples, then having out-of-correct-frame protein sequences in your target file won't matter much; you might get some small truncations at the 5' and 3' ends of the gene sequences recovered. If your target file does *not* contain sequences closely related to your samples, having out-of-frame protein sequences in your target file can matter a lot - you might see much larger truncations in the sequences recovered, or no sequence might be recovered at all for some genes.

**Long explanation:**

After HybPiper has assembled contigs for a given gene, it extracts coding sequence (that is, exons only) from the contigs via the following process:

1) Use the 'best' target file sequence for a given gene/sample as a reference protein (translated from the nucleotide sequence from the first codon position if a nucleotide target file was provided). This _should_ correspond to the target file sequence that is most similar to a given gene/sample. 
2) Align the reference protein to the nucleotide contigs using the program Exonerate, with an intron aware model (protein2genome).
3) Extract and concatenate regions of the contigs identified as exons in the Exonerate search (i.e. regions that, when translated, have good matches to the reference protein; note that Exonerate translates the contigs in all 6 frames when trying to align the protein reference).

As you might imagine given the above process, you can run in to issues when your reference target file protein sequence is translated in the wrong frame and is somewhat distantly related to the given sample - this is particularly true if it's been translated from the third wobble position, as these positions will likely have mutated at a higher rate and hence will often change the amino-acid coded for.

To illustrate this, here's a fragment of an Exonerate alignment between a target file reference protein and a nucleotide contig that's been assembled from sample reads. In this case, the reference protein (top) is closely related to the sample and has been translated in the correct frame:

```
  20 : PheIleMetProLeuAspLeuGlyAlaLysGlySerCysGlnIleGlyGlyAsnValSerThrA :  41
       ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
       PheIleMetProLeuAspLeuGlyAlaLysGlySerCysGlnIleGlyGlyAsnValSerThrA
 600 : TTTATTATGCCACTGGACTTAGGTGCTAAAGGTAGCTGCCAAATTGGTGGAAACGTTTCAACAA : 537

```

...whereas here is the alignment when the reference protein has been translated in the third frame:

```
  18 : ArgIleTyrTyrAlaThrGlyLeuGlyCysLysArg***LeuProAsnTrpTrpLysCysPheA :  39
       !:!||||||||||||||||||||| !!||| !!|||||||||||||||||||||||| !!||||
       GlnIleTyrTyrAlaThrGlyLeuArgCys***Arg***LeuProAsnTrpTrpLysArgPheA
 604 : CAGATTTATTATGCCACTGGACTTAGGTGCTAAAGGTAGCTGCCAAATTGGTGGAAACGTTTCA : 541

```

As you can see, the second alignment has lower similarity and contains stop codons etc, as you'd expect given the query reference 'protein' (and hence the contig hit) has been translated in the wrong frame. However, if the two sequences are fairly closely related, the translation of the nucleotide contig in the third frame can still match the reference 'protein' well enough for Exonerate to produce an alignment, which results in HybPiper recovering a sequence for this gene/sample.

If, however, the target file sequence is less closely related, it doesn't work as well. Here's an Exonerate alignment using the same contig but with a more distantly related protein reference (translated in the correct frame):

```
  20 : PheIleMetProLeuAspLeuGlyAlaLysGlySerCysHisIleGlyGlyAsnIleSerThrA :  41
       |||||||||||||||||||||||||||||||||||||||!!.||||||||||||:!!|||||||
       PheIleMetProLeuAspLeuGlyAlaLysGlySerCysGlnIleGlyGlyAsnValSerThrA
 600 : TTTATTATGCCACTGGACTTAGGTGCTAAAGGTAGCTGCCAAATTGGTGGAAACGTTTCAACAA : 537
```

This looks fine, but if the reference protein is translated in the third frame (i.e. sequence `N*SWLCVGEFKLLCGK*GVYYAA*PGSKR*LSHRWQHFN*RRWPTFHTLRFTSWKCTWS*SCLGRWNCSRYAYYFKERQHWI*SEALIYWK*RLTRNCH*NCNTY`), then the similarity falls beneath the threshold Exonerate requires to return an alignment; the result of the Exonerate search is empty, and HybPiper does not recover a sequence for this gene.

I was dealing with this out-of-frame issue in a bait file yesterday, and wrote a script that:

1) Takes a nucleotide target file in fasta format as input. 
2) For each sequence, identifies the first forwards frame that has no stop codons (or a single stop codon at the C-terminus of the translated frame if an optional flag is provided).
3) Recovers and writes these in-frame sequences to a new file with any trailing 3' nucleotides removed (i.e. it writes sequences that are a multiple of three, containing full codons only).
4) Writes any sequences that lack a translation without stop codons in any forwards frame to a separate file (these are not included in the first file written).
5) Optionally, produces a per-gene translated protein alignment of the 'fixed' in-frame sequences.

The latter alignments are useful because the script simply selects the first frame it can find that lacks stop codons in the protein translation. In most cases this should be the correct one, but if your target files sequences are short then there might be more than one frame fulfilling this criterion by chance. Visually scanning the alignments can identify any mis-translated sequences (I'll write something that automates this check at some stage...).

I've attached the gzipped script in case it's useful.

```
python get_inframe_targetfile.py -h 

usage: get_inframe_targetfile.py [-h] [--allow_terminal_stop_codons] [--alignments] [--concurrent_alignments INTEGER]
                                 [--threads_per_concurrent_alignment INTEGER]
                                 targetfile

Takes a nucleotide target file in fasta format as input. For each sequence, identifies the first forwards frame that has no stop codons, and recovers and
writes this sequence to a new file with any trailing 3' nucleotides removed ( i.e. it writes a sequence that is a multiple of three, containing full
codons only). If all forwards frames contain at least one stop codon, these sequences will be written to a second fasta file.

positional arguments:
  targetfile            Target file in nucleotide fasta format.

optional arguments:
  -h, --help            show this help message and exit
  --allow_terminal_stop_codons
                        When testing for open reading frames, allow a translated frame to have a stop codon at the C-terminus of the translated protein
                        sequence.
  --alignments          Create per-gene alignments for in-frame translated protein sequences.
  --concurrent_alignments INTEGER
                        Number of alignments to run concurrently. Default is 1.
  --threads_per_concurrent_alignment INTEGER
                        Number of threads to run each concurrent alignment with. Default is 1.

```

[get_inframe_targetfile.py.gz](https://github.com/mossmatters/HybPiper/files/8925361/get_inframe_targetfile.py.gz)



Cheers,

Chris

**Comment by chrisjackson-pellicle** [comment]
No problem!

I'm not sure if you've downloaded the script already yet, but I just realised it was parsing the target file gene names incorrectly for a HybPiper target file (I was using it on a file that wasn't formatted for HybPiper yet). I've just uploaded the fixed version. I'll also add the info and script to the wiki.

I'll close this issue now, but feel free to reopen it if there are issues/requests with the script.

Cheers,

Chris
