### ISSUE TITLE
hybpiper_stats.tsv file not generated with BLASTx hybpiper_assemble?

### ISSUE THREAD

**Issue by joyceem** [mossmatters/HybPiper#83]
Hi there,

Thanks for the new version of HybPiper - loving how quick it is!

I've got an issue with retrieving the hybpiper_stats. We've run hybpiper_assemble against a nucleotide target file with BWA, and then separately with the nucelotide target file but without the --bwa flag to check the difference in recovery of loci using a translated target file + BLASTx vs. DNA target file + BWA.

Both runs of hybpiper_assemble worked, and all outputs look fine.

When we run hybpiper_stats, it works with the DNA+BWA run and all the output is generated. However, when we run hybpiper_stats on the AA+BLASTx run, the seq_lengths.tsv table is generated and we can generate a heatmap, but the summary hybpiper_stats file is not generated. We get the error:

> > A sequence length table has been written to file: seq_lengths.tsv
> Traceback (most recent call last):
>   File "/home/student/applications/miniconda3/envs/hybpiper/bin/hybpiper", line 10, in <module>
>     sys.exit(main())
>   File "/home/student/applications/miniconda3/envs/hybpiper/lib/python3.9/site-packages/hybpiper/assemble.py", line 1689, in main
>     args.func(args)
>   File "/home/student/applications/miniconda3/envs/hybpiper/lib/python3.9/site-packages/hybpiper/assemble.py", line 1502, in hybpiper_stats_main
>     hybpiper_stats.main(args)
>   File "/home/student/applications/miniconda3/envs/hybpiper/lib/python3.9/site-packages/hybpiper/hybpiper_stats.py", line 353, in main
>     stats_dict[name] += enrich_efficiency_blastx(blastxfile, name)
>   File "/home/student/applications/miniconda3/envs/hybpiper/lib/python3.9/site-packages/hybpiper/hybpiper_stats.py", line 156, in enrich_efficiency_blastx
>     raise ValueError(f'No file containing total input paired or single-end read count found!')
> ValueError: No file containing total input paired or single-end read count found!

This occurs when directing to both the amino acid and DNA target file for this run, i.e.:
`hybpiper stats -t_aa ../target_file/meli_ruta_sima_targets_translated.fasta gene ../samples_all.txt`
and
`hybpiper stats -t_dna ../target_file/meli_ruta_sima_targets.fasta gene ../samples_all.txt`

Do you have any idea what might be causing this issue?

Many thanks in advance,
Lizzy

**Comment by chrisjackson-pellicle** [comment]
G'day Lizzy,

Hmm, I'm not sure what the problem is, yet - everything appears to be working as expected on my test data.

When using BLASTx/DIAMOND, in each sample folder there should be a file called `total_input_reads_paired.txt` (if paired reads were used), or `total_input_reads_single.txt` (if single-end reads were used). These text files just contain a number corresponding to the number of reads in your input read files; they get written during the read distribution step of the pipeline. The error you're seeing is caused by `hybpiper stats` not being able to find one of these files.

Are these files present in your sample folders? For example, after running the tutorial data with BLASTx, a `ls` of the sample folder for `EG30` returns:

```
EG30.blastx
EG30_genes_derived_from_putative_chimeric_stitched_contig.csv
EG30_genes_with_long_paralog_warnings.txt
EG30_genes_with_paralog_warnings_by_contig_depth.csv
EG30_genes_with_stitched_contig.csv
EG30_hybpiper_assemble_2022-06-16-16_13_49.log
exonerate_genelist.txt
gene001
gene002
gene006
gene012
gene026
gene030
gene074
gene079
gene111
gene293
gene298
gene461
gene660
genes_with_seqs.txt
gnu_parallel_log.txt
spades_genelist.txt
spades_initial_commands.txt
spades.log
target_tallies.txt
test_targets_translated.fasta
test_targets_translated.fasta.pdb
test_targets_translated.fasta.phr
test_targets_translated.fasta.pin
test_targets_translated.fasta.pot
test_targets_translated.fasta.psq
test_targets_translated.fasta.ptf
test_targets_translated.fasta.pto
total_input_reads_paired.txt
```

Cheers,

Chris

**Comment by joyceem** [comment]
Hi Chris,

Thanks for the fast reply! Yep - I've just checked the sample folders and we seem to have all those outputs including a `total_input_reads_paired.txt` and `total_input_reads_unpaired.txt` for each sample, which contains a number, so seems to be ok there...

Many thanks
Lizzy

**Comment by chrisjackson-pellicle** [comment]
Hmm, again! 

Can you please:

1) Post the output of the command `hybpiper --version` (don't worry the ASCII art :) ).
2) Upload your `samples_all.txt` file here.
3) Confirm that you're running the `hybpiper stats` command from the directory containing the sample folders.

If the version returned by item 1 is lower than `hybpiper 2.0.1rc build 9`, are you able to update HybPiper? Running the command `conda install -c chrisjackson-pellicle hybpiper` within your conda `hybpiper` environment should update you to build 9. If it doesn't, you might need to remove the hybpiper package and reinstall it.

Cheers,

Chris

**Comment by chrisjackson-pellicle** [comment]
Ah, apologies - it turns out I had only pushed the OSX version of build 9 to the conda channel. It should now be available for Linux, too.

Regardless of the build version, I suspect that it is your failed samples that are causing the issue. I'm not clear on how, though, if these sample folders do contain a `total_input_reads_paired.txt` and `total_input_reads_unpaired.txt` file.

To try to isolate the problem, can you make a new `sample_all.txt` file containing only a few sample names (for samples that **did** recover sequences), and run `hybpiper stats` with this new file? If that works, can you then add a sample name for a failed sample to the new `sample_all.txt` file, and run `hybpiper stats` again?

Sorry for the laborious troubleshooting!

Cheers,

Chris

**Comment by joyceem** [comment]
Hi Chris,

No worries! 

Ok, so we updated hybpiper to build 9 - still the same issue when we run `hybpiper stats` with `samples_all.txt`.

But, then we did as you suggested and ran `hybpiper stats` on a reduced samples list with a few successful samples, and it worked, generating our `hybpiper_stats.tsv` file. So, the issue seems to be that the script crashes when a failed sample is in the list!

The sample responsible had dodgy sequencing, so failed trimmomatic and hybiper and then didn't generate the `total_input_reads_*.txt` files. Here are the log files for trimmomatic and hybpiper for that sample:

[log_MELI_Guarea_pubescens_IDS10901-trim-out.txt](https://github.com/mossmatters/HybPiper/files/8965392/log_MELI_Guarea_pubescens_IDS10901-trim-out.txt)
[log_MELI_Guarea_pubescens_IDS10901-hybpiper-err.txt](https://github.com/mossmatters/HybPiper/files/8965393/log_MELI_Guarea_pubescens_IDS10901-hybpiper-err.txt)

Thanks for your time on this!
Lizzy

**Comment by chrisjackson-pellicle** [comment]
Excellent, glad it's working!

I've just pushed a new build (build 10), which should deal with this situation more cleanly in future pipeline runs. Errors with malformed `*.fastq` files are now captured during the read distribution step, and the error is logged to the sample log file, e.g.:

> [ERROR]:   Malformed FASTQ file! Please check your input FASTQ files (/Users/chrisjackson/
>            Desktop/Research/19_HybPiper2.0/01_testing/01_test_dataset/01_reads/
>            EG30_R1_test_malformed.fastq, /Users/chrisjackson/Desktop/Research/
>            19_HybPiper2.0/01_testing/01_test_dataset/01_reads/EG30_R2_test.fastq) and try
>            again. Error is: Lengths of sequence and quality values differs for
>            M00223:34:000000000-AAJCV:1:1111:20131:6317 1:N:0:29 (264 and 684).

Also, if `hybpiper stats`  can't find the expected input read count files (when using BLASTx/DIAMOND), it now reports the corresponding sample name along with some instructions, e.g.:

> [WARNING]: No file containing total input paired or single-end read count found for sample
>            EG30!. Please check the log file for this sample. If "hybpiper assemble" can
>            not be run successfully for this sample, please remove it from your namelist
>            text file before running "hybpiper stats".

Cheers,

Chris

P.S. Incidentally - a malformed FASTQ file like this can sometimes be caused by file copy issues. If the `MELI_Guarea_pubescens_IDS1090` sample is important (and the read files were copied from an original location) it might be worth copying them again and re-trying.
