### ISSUE TITLE
hybpiper retrieve_sequences in directory without write permission

### ISSUE THREAD

**Issue by mossmatters** [mossmatters/HybPiper#85]
A couple of issues/improvements for `hybpiper retrieve_sequences`:

- I was unable to run `hybpiper retrieve_sequences` specifying a directory (`NovaSeq768`) containing HybPiper output:

```
hybpiper retrieve_sequences --single_sample_name ABRONIAseq141 dna -t_dna /scratch/sherpric/NovaSeq768/mega353.fasta --hybpiper_dir /scratch/sherpric/NovaSeq768/
```

I do not have write access to the `NovaSeq768` directory but there is HybPiper output for the sample `ABRONIAseq141` in there. I was able to run it in the "other" direction by being in `NovaSeq768` and specifying `--fasta_dir` but I'm not sure why `hybpiper_dir` didn't work.

- Relatedly, the output for a single sample is currently set as `FNA.fasta` which is not very informative. Should we instead use the value for `--single_sample_name` to specify the output file name?

**Comment by chrisjackson-pellicle** [comment]
Ah, I hadn't implemented the `hybpiper_dir` path search when using the `--single_sample_name` flag. Should be fixed in `build 11` (repo and conda pushed). Also, the recovered fasta file name should now have the value of `--single_sample_name` as a prefix, e.g. `EG30_FNA.fasta`, `EG30_supercontig.fasta`, etc. 

Can you test it on your data, please?

**Comment by mossmatters** [comment]
Build 11 works as expected, thanks!
