### ISSUE TITLE
Issue with recovery_heatmap

### ISSUE THREAD

**Issue by GavSmy** [mossmatters/HybPiper#94]
I am unable to generate a heatmap using recovery_heatmap. It does not generate a .png because of a ValueError. There are no duplicate sample names in seq_lenths.tsv
"ValueError("Index contains duplicate entries, cannot reshape")
See attached screenshot
![Screen Shot 2022-08-22 at 11 58 49 AM](https://user-images.githubusercontent.com/111782042/185979470-e5d92839-490d-4df7-96e9-398dcaa62da5.png)

**Comment by chrisjackson-pellicle** [comment]
Hi @GavSmy,

I'm on parental leave until mid November, so I'll have very limited opportunity to properly respond to issues until then.  Can you upload your seq_lengths.tsv file, please? 

I'm wondering if this is some sort of issue with 'pandas' due to your use of miniconda2 rather than miniconda3, but I don't have capacity to test it at the moment. Are you able to install minconda3, then Hybpiper, and try that? 

Cheers, Chris

**Comment by GavSmy** [comment]
Hi Chris,
A delayed response, but I wanted to let you know that there were two problems: a sample id mismatch and a few incomplete assemblies. Once I fixed these issues I had no problem. Thank you for your response.

**Comment by chrisjackson-pellicle** [comment]
Great - thanks for letting me know!
