### ISSUE TITLE
Very slow I/O?

### ISSUE THREAD

**Issue by SethMusker** [mossmatters/HybPiper#96]
Hi guys,

I've been using v.2.0.1 on a SLURM cluster and noticed extremely slow I/O for `assemble` when not using the `--distribute_hi_mem` flag.

I'm talking estimated times of probably several weeks, versus less than a minute when using the hi mem flag.

Example log files attached. Same sample but read counts differ because I did some subsampling before rerunning.
[718432_assemble_20.err.txt](https://github.com/mossmatters/HybPiper/files/9498549/718432_assemble_20.err.txt)
[assemble_20.err.txt](https://github.com/mossmatters/HybPiper/files/9498551/assemble_20.err.txt)

This seems to be affecting the `stats`, `paralog_retriever`  and `retrieve_sequences` modules too, as they're all extremely slow (8+ hours to process 300 genes and 300 samples, roughly). If reading into memory would help, is there any chance a hi_mem option could be added for these? 

I realise this may have something to do with the fact that I'm running this on a cluster. However, I have bash and R scripts that do lots of I/O that run perfectly fine on it (also in scratch).

Cheers,
Seth

**Comment by chrisjackson-pellicle** [comment]
Hi Seth,

I'm surprised by the degree of I/O slowdown there! Have you tested this a couple of times on different nodes? Just wanting to rule out a transient problem with your HPC cluster. 

Regarding the slow-downs you're seeing with `stats`, `paralog_retriever` and `retrieve_sequences`: it's a bit tricky to diagnose these problems across different HPCs/file systems. To help with this, I've just pushed an update (`hybpiper 2.0.1rc build 13`) that adds the optional parameter `--run_profiler` to each hybpiper sub-command. If used, the sub-command will be run with the Python [cProfile](https://docs.python.org/3/library/profile.html#introduction-to-the-profilers), and the profile stats will be written to a `*.csv` file (i.e. `retrieve_sequences_cprofile.csv`, `stats_cprofile.csv`, etc). Not that if running `hybpiper assemble` with this flag, the `*.csv` file will be written to the sample directory. 

Are you able to run the problematic sub-commands on your HPC using a couple of samples, using the `--run_profiler` flag, and upload the profile `*.csv` files? That'll let me see where the main slow-downs occur. Note that running with the profiler adds some processing overhead, so the run time will be longer than usual. The ratio of times spent in different function calls etc should still be informative, though.

Cheers,

Chris

**Comment by SethMusker** [comment]
Hi Chris,

Another late reply, sorry.

I didn't get around to doing this. In the end `stats` did eventually complete, but I ended up having to write a bash script to retrieve the sequences as my jobs were timing out after 24 hr. I have a bit more time now and I'm working on a new dataset (with the latest release) on the same cluster, so I'll report back on any problems or lack thereof.

Regarding profiling (and before having actually done any...), I came across this interesting talk by Emery Berger in which he introduces Scalene. IMO, worth a watch and might be worth trying, especially in this case?
https://www.youtube.com/watch?v=vVUnCXKuNOg
https://github.com/plasma-umass/scalene

S

**Comment by chrisjackson-pellicle** [comment]
Hi Seth,

Good to hear you got it working, although not great that it required custom scripting!

Thanks for sending that talk and repo through - I watched the talk yesterday. Scalene certainly looks promising, but at the moment it seems to have some issues with HybPiper:

1) The default web output (with the nice pie charts, hover-over details etc) doesn't render the line-by-line output properly for the `assemble.py` script (the entry point to the HybPiper pipeline) - the actual HybPiper code for each line is missing. I tracked this down to the point in the `assemble.py` code where it changes to the sample directory: https://github.com/mossmatters/HybPiper/blob/274dcbe71333b6fffae19f48c78dc4a28079cc83/hybpiper/assemble.py#L1278 If you change the HybPiper code to exit before this point, the web output appears to work as expected. 

2) Running with default settings (i.e. profiling both memory and cpu) causes the SPAdes assemblies to crash (SPAdes log files have the error `== Error ==  system call for: "['/Users/chrisjackson/miniconda3/envs/hybpiper_2.1.1/bin/spades-core', '/Users/chrisjackson/Desktop/Research/19_HybPiper2.0/01_testing/01_test_dataset/hybpiper/EG30/gene001/gene001_spades/K21/configs/config.info']" finished abnormally, OS return value: -11`). This doesn't seem to be caused by reduced memory due to the memory overhead of Scalene itself, as my computer had plenty of free RAM. One hacky way to get a memory/cpu profile of the full HybPiper assembly pipeline (excluding the SPAdes step) is to run HybPiper once without Scalene, thus producing the SPAdes output, and then run it again with Scalene - SPAdes won't re-run run assemblies that have already completed, so it'll move on and successfully profile the next pipeline step (Exonerate). Running Scalene with just cpu profiling seems ok - SPAdes runs fine.

3) I could only get Scalene to produce a report when running HybPiper with a small test read files on my Mac - running on a Linux server with larger read files either produced empty reports, or generated errors (`Scalene error: received signal SIGSEGV` was one, but there were others that appeared to be related (perhaps...) to the module `pebble`, which HybPiper uses for multiprocessing). I also saw the `SIGSEGV` error when running the small dataset on the Linux server - in the time I spent on it, I couldn't work out if there was a pattern, or if the errors were 'random'. 

Running Scalene using options for command line only and html report (`scalene --cli --cpu --html --outfile cpu_all.html --profile-all --profile-exclude python3.9 assemble.py --- assemble` etc) worked better, and provided a useful per-line and per-function report. However, SPAdes will still only run when profiling the cpu only, so you still need to run HybPiper once first to get a cpu/memory profile of downstream steps.

I've attached a couple of Scalene profile reports from running Scalene/HybPiper with the small test dataset on my Mac, in case you're interested: [scalene_reports.zip](https://github.com/mossmatters/HybPiper/files/10234480/scalene_reports.zip). These are from running HybPiper once, then running again with Scalene profiling both memory and cpu. You'll see in the file `spades_first_then_cpu_and_memory_web.html` that the per line code is missing for `assemble.py`, but you can match the line numbers with the code in the file `spades_first_then_cpu_and_memory_cli.html`. As you might expect (at least with small read files), the greatest time is spent running external programs - `blast`/`DIAMOND`, `SPAdes`, `Exonerate` and `bbmap.sh`. 

So, overall I'll definitely keep an eye on Scalene, but it might take a few more releases to iron out the kinks!

Cheers,

Chris

**Comment by SethMusker** [comment]
Hi Chris,

Sorry for taking ages to respond. I have a strong feeling the issue was with the cluster I was running on, which seems to generally have an I/O problem. I've come to realise that anything that requires copying, removing or unzipping takes much longer than it ought to. Given that, I reckon you can go ahead and close this issue if you like. Sorry if this felt like a waste of time. It was interesting to read about your experience with Scalene. 

Cheers,
Seth

**Comment by chrisjackson-pellicle** [comment]
My turn for a late response - no worries at all!

Cheers,

Chris
